# Generated by Django 4.0.5 on 2022-06-08 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('comment_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('photo_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modifier', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CommentsApp.comment')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CommentsApp.poster')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='poster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CommentsApp.poster'),
        ),
    ]
