# Generated by Django 4.0.5 on 2022-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
