# Generated by Django 4.0.5 on 2022-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0002_remove_poster_photo_url_comment_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
