# Generated by Django 4.0.5 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0004_alter_upvote_poster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='poster_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CommentsApp.poster'),
        ),
    ]
